name: "Release"

on:
  push:
    tags:
      - v*
    branches:
      - v4
jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy Binary
        run: |
          make build-reproducible-all

      - name: List files
        run: ls -R
        
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            build/bcnad_linux_arm64
            build/bcnad_linux_amd64
            build/bcnad_sha256.txt
